title: 안광빈
author: 안광빈
email: rhkdqlsdml10@gmail.com
description: macOS, iOS Developer
html_lang: ko

name: 안광빈
tagline: macOS, iOS Developer
portfolio_image: "assets/portfolio.png"

navigation:
  - title: 이력서
    url: /resume
  - title: 경력 기술서
    url: /career
  - title: 포트폴리오
    url: /portfolio
  - title: 기술 블로그
    url: /blog

sass:
  sass_dir: _sass

plugins:
  - jekyll-seo-tag
